In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import lane_detection
IMAGE_FILE = "testing.png"
img = cv2.imread(IMAGE_FILE)

In [2]:
lines = lane_detection.detect_lines(img, 49, 50, 3, 500, 40)
print(lines)
plt.imshow(cv2.cvtColor(lane_detection.draw_lines(img, lines), cv2.COLOR_BGR2RGB))
plt.show()

[[[3052 1178 3726 1309]]

 [[1044 2066 1405 1465]]

 [[1006 2132 1393 1488]]

 [[1066 2026 1433 1415]]

 [[1427 2133 1553 1587]]]


In [ ]:
lane_detection.get_slopes_intercepts(lines)

In [ ]:
lanes = lane_detection.detect_lanes(lines)
print(lanes)

In [ ]:
lane_detection.draw_lanes(img, lanes)
plt.imshow(cv2.cvtColor(lane_detection.draw_lanes(img, lanes), cv2.COLOR_BGR2RGB))
plt.show()