In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import lane_detection

In [3]:
IMAGE_FILE = "rov_pool.jpg"

In [4]:
img = cv2.imread(IMAGE_FILE)

In [6]:
lines = lane_detection.detect_lines(img, 50, 90,3)
print(lines)

[[[1726  624 1739  628]]

 [[1131 1033 1137 1044]]

 [[ 816  701  819  711]]

 [[1298 1049 1308 1047]]]
